# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Aug  4 12:16:55 PDT 2015
#
#/ usage: docker-machine:inspect [ --format <>]  --machine <>  --machine-storage-path <${MACHINE_STORAGE_PATH:-}> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --format) rerun_option_check $# $1; FORMAT=$2 ; shift ;;
            --machine) rerun_option_check $# $1; MACHINE=$2 ; shift ;;
            --machine-storage-path) rerun_option_check $# $1; MACHINE_STORAGE_PATH=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$MACHINE" ] && { echo >&2 "missing required option: --machine" ; return 2 ; }
    [ -z "$MACHINE_STORAGE_PATH" ] && { echo >&2 "missing required option: --machine-storage-path" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export MACHINE_STORAGE_PATH
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${FORMAT:=}
: ${MACHINE:=}
: ${MACHINE_STORAGE_PATH:=}


